### PR TITLE
DP Keras Model with Vectorized Map and XLA optimization

### PR DESCRIPTION
**Pull request by pranavsubramani**
Here we upload an alternative to the Keras model using vectorizated map and XLA acceleration (if desired). To this end, we:

- Created a new directory, privacy/keras_models which contains the optimizer file
- Added a tutorial of how to use it (similar to the previous tutorials)

Please let us know if there's anything else missing and we can send that across as well.

### CODE REVIEW

**Comment by pranavsubramani** [comment]
@googlebot I signed it!

**Comment by n2cholas** [comment]
@googlebot I signed it!

**Comment by n2cholas** [comment]
@googlebot I consent.

**Review by schien1729 — APPROVED** [review]

**Comment by schien1729** [comment]
Thanks! This change will now go into internal review and then should appear back in the repo, properly credited to you.

**Pull request merged**
